### PR TITLE
Feature readme enhancement

### PR DESCRIPTION
**Pull request by truenicfel**
## Description

Readme improved and status updated.

### CODE REVIEW

**Comment by DManstrator** [comment]
[From the ReadMe:](https://github.com/ob-vss-ss18/ppl-stock/pull/10/files#diff-04c6e90faac2675aa89e2176d2eec7d8R72)
```
+#### Not using a Fork
+
+First fork the main repository (github.com/ob-vss-ss18/ppl-stock). Now clone:
```
Sure you did not mistype there?

**Comment by truenicfel** [comment]
@DManstrator thx for reading through it. I corrected the error mentionend above. Feel free to merge when you are ok with everything.

Quick FYI: You can start discussions on specific  code by going to 'Files changed' ([here](https://github.com/ob-vss-ss18/ppl-stock/pull/10/files)) and when hovering over lines clicking on the blue '+'. People can even answer to your comments.

**Comment by DManstrator** [comment]
@truenicfel Thanks for feedback. Still two questions:
- Are new branches needed when forking the repository before? Shouldn't be a problem imo.
- Why not using the [development-branch](https://github.com/ob-vss-ss18/ppl-stock/tree/devBranch) for such PRs? I don't think that a new branch for every PR would make that much sense.

To your FYI: I wanted to quote multiple lines and not just one so I copied it before trying for hours. And yeah, I read the [GitHub Article](https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/) about it, didn't help much tho.

**Comment by truenicfel** [comment]
To answer your questions:

- you don't need a branch to fork a repository. Forking is simply creating a private copy of an existing repository (hope that is what your question was about)
-  you do not use a single development branch for this because you don't want to interfere with the changes of other developers. instead everyone simply creates his own branch. The approved changes then get merged into master branch.

**Comment by DManstrator** [comment]
@truenicfel With the first thing, I wanted to ask if it's needed to create a new branch for the forked repository, why not just using the master branch of the fork and doing the PR from there.

And how about creating a single dev branch for each developer, still a bad idea?

**Comment by DManstrator** [comment]
@truenicfel Could you add the Link to our Heroku Project to the ReadMe file? Then we don't need another PR for that.

And just in case you like to do you could update the Team in the ReadMe (missing GitHub links). Thanks in advance.

**Comment by truenicfel** [comment]
The usual way to do it is to create feature branches. You merge these and then you create a new one. If you prefer to use a single dev branch, feel free to do that.

I have added everything you guys requested.

**Comment by DManstrator** [comment]
@truenicfel Not the only thing we really needed, the linked Heroku URL.

**Pull request merged**
